### ISSUE TITLE
Release 1.33 meta tasks

### ISSUE THREAD

**Issue by callahad** [nginx/unit#1399]
- [x] Review all open PRs
- [x] Ensure changelog is up to date, select shortlist of user-facing changes to highlight (@avahahn + @ac000)
- [x] Write up user-facing highlights (@Jcahilltorre)
- [x] Review the commits immediately prior to 1.32 to see if there are any steps we might miss (@ac000)
- [x] Update wasmtime version for the `wasm-wasi-component` language module (@avahahn)
- [x] Re-review the release checklist (@callahad)

...and then hand it off to SysEng to make the release :)

**Comment by callahad** [comment]
Those will be plucked out by @avahahn and @ac000 as part of the bullet immediately above the handoff task :)

**Comment by ac000** [comment]
For the changelog I have the following (selected from `git shortlog 1.32.0..master`)

Listed in feature/change/bugfix order

```
<change type="feature">                                                         
<para>                                                                          
show list of loaded language modules in the /status endpoint.                   
</para>                                                                         
</change>                                                                       
                                                                                
<change type="feature">                                                         
<para>                                                                          
make the number of router threads configurable.                                 
</para>                                                                         
</change>                                                                       
                                                                                
<change type="feature">                                                         
<para>                                                                          
make the listen(2) backlog configurable.                                        
</para>                                                                         
</change>

<change type="feature">                                                         
<para>                                                                          
add fuzzing via oss-fuzz.                                                       
</para>                                                                         
</change>

<change type="feature">                                                         
<para>                                                                          
add Python application factory support.                                         
</para>                                                                         
</change> 

<change type="feature">                                                         
<para>                                                                          
add chunked request body support.                                               
</para>                                                                         
</change>                                                                       
                                                                                
<change type="feature">                                                         
<para>                                                                          
add "if" option to the "match" object.                                          
</para>                                                                         
</change>

<change type="change">                                                          
<para>                                                                          
unit now builds with -std=gnu11 (C11 with GNU extensions).                      
</para>                                                                         
</change>                                                                       
                                                                                
<change type="change">                                                          
<para>                                                                          
unit now creates the full directory path for the PID file and control socket.   
</para>                                                                         
</change>

<change type="change">                                                          
<para>                                                                          
build system improvements, including pretty printing the make output and        
enabling various make variables to influence the build process (see:            
make help).                                                                     
</para>                                                                         
</change>                                                                       
                                                                                
<change type="change">                                                          
<para>                                                                          
better detection of available runnable CPUs on Linux.                           
</para>                                                                         
</change>                                                                       
                                                                                
<change type="change">                                                          
<para>                                                                          
default listen(2) backlog on Linux now defaults to Kernel default.              
</para>                                                                         
</change>

<change type="bugfix">                                                          
<para>                                                                          
don't create the $runstatedir directory which triggered an Alpine packaging     
error.                                                                          
</para>                                                                         
</change>

<change type="bugfix">                                                          
<para>                                                                          
wasm-wasi-component application process hangs after receiving restart signal    
from the control endpoint.                                                      
</para>                                                                         
</change>

<change type="bugfix">                                                          
<para>                                                                          
njs variables accessed with a JS template literal should not be cacheable.      
</para>                                                                         
</change>                                                                       
                                                                                
<change type="bugfix">                                                          
<para>                                                                          
don't modify REQUEST_URI.                                                       
</para>                                                                         
</change>                                                                       
                                                                                
<change type="bugfix">                                                          
<para>                                                                          
properly handle deleting arrays of certificates.                                
</para>                                                                         
</change>
```

**Comment by ac000** [comment]
OK, forget the previous comment.

To keep just _one_ source of truth (docs/changes.xml/[CHANGES](https://github.com/ac000/unit/blob/1.33-prep/CHANGES)), I've started https://github.com/nginx/unit/pull/1401

**Comment by ac000** [comment]
As well as the _changelog_, I think we should start providing the output of `git shortlog ...` as the Git (and other projects do), e.g <https://lore.kernel.org/git/xmqqzfq0i0qa.fsf@gitster.g/>

And let's not forget to highlight our external contributors... currently

```
Alejandro Colomar (12)
Arjun (13)
Costas Drongos (1)
Gourav (2)
Remi Collet (1)
dependabot[bot] (5)
```

I think we can ignore dependabot!

**Comment by ac000** [comment]
We should probably give Arjun (@pkillarjun) special mention for his fuzzing work...

**Comment by Jcahilltorre** [comment]
I will open a PR with the skeleton file for the news page

**Comment by ac000** [comment]
I have created a [draft](https://gist.github.com/ac000/ac373679fc59a149c77cee64dbb78fa0) of the 1.33.0 announce email (sent to the Unit mailing list), somewhat inspired by git's announce emails.

If anyone notices their favourite feature missing, let me know, or even better, send text!

@Jcahilltorre Feel free to lift bits out of there for the website.

**Comment by ac000** [comment]
Hey folks, still a few outstanding things before we can release...

* [https://github.com/nginx/unit/pull/1337](https://github.com/nginx/unit/pull/1337)
@callahad Do you want to merge this or have someone else do it?

* [https://github.com/nginx/unit/pull/1371](https://github.com/nginx/unit/pull/1371)
Still requires a review...

* [https://github.com/nginx/unit/pull/1402](https://github.com/nginx/unit/pull/1402)
This needs a review and would be good to merge before the below wasm-wasi-component updates

* [https://github.com/nginx/unit/issues/1392](https://github.com/nginx/unit/issues/1392)
@avahahn @javorszky AIUI this is done?, but needs a pull-request and review
Once that is done, I plan to merge (assuming it just works) the fix for

* [https://github.com/nginx/unit/issues/1312](https://github.com/nginx/unit/issues/1312)
